services:
  db:
    image: postgres:16
    container_name: animeflix_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: super
      POSTGRES_DB: animeflix
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

